#name: CMake
#
#on: [push, pull_request]
#
#env:
#  BUILD_TYPE: Release
#
#jobs:
#  build:
#    runs-on: ${{ matrix.os }}
#    strategy:
#      matrix:
#        os: [macos-latest, windows-latest]
#
#    steps:
#      - uses: actions/checkout@v3
#        with:
#          submodules: recursive
#
#      - name: Create Build Environment
#        run: cmake -E make_directory ${{runner.workspace}}/build
#
#      - name: Configure CMake
#        shell: bash
#        working-directory: ${{runner.workspace}}/build
#        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE
#
#      - name: Build
#        working-directory: ${{runner.workspace}}/build
#        shell: bash
#        run: cmake --build . --config $BUILD_TYPE

name: PngCI

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: "Preparation"
        uses: actions/checkout@v3

      - name: "(JUCE) Clone Repository"
        uses: actions/checkout@v3
        with:
          repository: juce-framework/JUCE
          path: ${{runner.workspace}}/PngToFilmstrip/JUCE

      - name: "(JUCE) Create Build Environment"
        working-directory: ${{runner.workspace}}/PngToFilmstrip/JUCE
        run: cmake -E make_directory ${{runner.workspace}}/PngToFilmstrip/JUCE/build

      - name: "(JUCE) Configuration"
        working-directory: ${{runner.workspace}}/PngToFilmstrip/JUCE/build
        run: cmake ${{runner.workspace}}/PngToFilmstrip/JUCE

      - name: "(JUCE) Build"
        working-directory: ${{runner.workspace}}/PngToFilmstrip/JUCE/build
        run: cmake --build .

      - name: "(PngToFilmstrip) Create Build Environment"
        working-directory: ${{runner.workspace}}/PngToFilmstrip
        run: cmake -E make_directory ${{runner.workspace}}/PngToFilmstrip/build

      - name: "(PngToFilmstrip) Configuration"
        working-directory: ${{runner.workspace}}/PngToFilmstrip/build
        run: cmake ${{runner.workspace}}/PngToFilmstrip

      - name: "(PngToFilmstrip) Build"
        working-directory: ${{runner.workspace}}/PngToFilmstrip/build
        run: cmake --build . #--config $BUILD_TYPE