name: PngCI

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        #os: [ubuntu-latest, windows-latest, macos-latest]
        os: [ windows-latest]

    steps:
      - name: "Preparation"
        uses: actions/checkout@v3

      - name: "Install JUCE's Linux Deps"
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update && sudo apt install libasound2-dev libjack-jackd2-dev \ladspa-sdk \libcurl4-openssl-dev  \libfreetype6-dev \libx11-dev libxcomposite-dev libxcursor-dev libxcursor-dev libxext-dev libxinerama-dev libxrandr-dev libxrender-dev \libwebkit2gtk-4.0-dev \libglu1-mesa-dev mesa-common-dev

      - name: "(JUCE) Clone Repository"
        uses: actions/checkout@v3
        with:
          repository: juce-framework/JUCE
          path: ${{runner.workspace}}/PngToFilmstrip/JUCE

      - name: "(JUCE) Create Build Environment"
        working-directory: ${{runner.workspace}}/PngToFilmstrip/JUCE
        run: cmake -E make_directory ${{runner.workspace}}/PngToFilmstrip/JUCE/build

      - name: "(JUCE) Configuration"
        working-directory: ${{runner.workspace}}/PngToFilmstrip/JUCE/build
        run: cmake ${{runner.workspace}}/PngToFilmstrip/JUCE

      - name: "(JUCE) Build"
        working-directory: ${{runner.workspace}}/PngToFilmstrip/JUCE/build
        run: cmake --build .

      - name: "(PngToFilmstrip) Create Build Environment"
        working-directory: ${{runner.workspace}}/PngToFilmstrip
        run: cmake -E make_directory ${{runner.workspace}}/PngToFilmstrip/build

      - name: "(PngToFilmstrip) Configuration"
        working-directory: ${{runner.workspace}}/PngToFilmstrip/build
        run: cmake ${{runner.workspace}}/PngToFilmstrip

      - name: "(PngToFilmstrip) Build"
        working-directory: ${{runner.workspace}}/PngToFilmstrip/build
        run: cmake --build . #--config  ${{ env.BUILD_TYPE }}

      - name: "Test"
        working-directory: ${{ env.BUILD_DIR }}
        run: ctest --output-on-failure -j4 -VV